{% set name = "pysbf2" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysbf2-{{ version }}.tar.gz
  sha256: da6c4e0e371215061c306476c2eab81a9083b70678acf139ca6a78044c72496b
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pynmeagps >=1.0.50
    - pyrtcm >=1.1.6

test:
  imports:
    - pysbf2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pysbf2
  description: Python library for parsing and generating Septentrio SBF GNSS protocol messages.
  summary: SBF protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pysbf2
  dev_url: https://github.com/semuconsulting/pysbf2

extra:
  recipe-maintainers:
    - semuadmin
